---

name: Build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: docker.pkg.github.com/dovnaralexander/github-actions-docker-generic/test:rc
