---

name: CD

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release:
        description: 'GitHub Release to deploy'
        required: false
        default: ''
      tag:
        description: 'Docker Tag to deploy'
        required: false
        default: 'latest'

jobs:
  prepare:
    name: Preparation
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GROUP_TOKEN }}
  deploy:
    name: Deployment to Jelastic
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Update
        run: echo 'deploying the latest release docker'
      - name: Prepare env vars
        id: tag
        run: .github/docker-tag.sh
        env:
          AUTO_TAG: ${{ github.event.release.name }}
          RELEASE: ${{ github.event.inputs.release }}
          TAG: ${{ github.event.inputs.tag }}
      - name: Set tag to deploy
        run: echo '::set-env name=CURRENT::rollback'
      - name: Test deployment
        run: |
          echo "${{ steps.tag.outputs.tag }} deployment"
          echo 'let's try random exit
          exit $(($RANDOM%2))

  release:
    name: Release update
    runs-on: ubuntu-latest
    if: success()
    needs: deploy
    steps:
      - name: Update release
        uses: meeDamian/github-release@2.0
        if: github.event_name == 'release'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          allow_override: true
          draft: false
          name: ${{ github.event.release.name }}

  rollback:
    name: Rollback the deployment
    runs-on: ubuntu-latest
    if: failure()
    needs: deploy
    steps:
      - name: Rolling back
        run: echo "rolling back the latest release docker to $CURRENT version!"
