---

name: CD

on:
  release:
    types: [prereleased]
  workflow_dispatch:
    inputs:
      release:
        description: 'GitHub Release to deploy'
        required: false
        default: ''
      tag:
        description: 'Docker Tag to deploy'
        required: false
        default: 'latest'

jobs:
  prepare:
    name: Docker tag preparation
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GROUP_TOKEN }}
  deploy:
    name: Deployment to Jelastic
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run Update
        run: echo 'deploying the latest release docker'
      - name: Test deployment
        run: |
          echo 'let's try random exit
          exit $(($RANDOM%2))
      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          release: ${{ github.event.release.name }}
  rollback:
    name: Rollback the deployment
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Rolling back
        run: echo 'rolling back the latest release docker'
