---

name: CD

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release:
        description: 'GitHub Release to deploy'
        required: false
        default: ''
      tag:
        description: 'Docker Tag to deploy'
        required: false
        default: 'latest'

jobs:
  prepare:
    name: Logging in to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GROUP_TOKEN }}
  deploy:
    name: Deployment to Jelastic
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - name: Run Update
        run: echo 'deploying the latest release docker'
      - name: Set tag to deploy
        uses: allenevans/set-env@v1.0.0
        with:
          TAG: ${{ join([ github.event.release.name, github.event.inputs.release, github.event.inputs.tag ], "" ) }}
          CURRENT: ROLLBACK
      - name: Test deployment
        run: |
          echo "$TAG deployment"
          echo 'let's try random exit
          exit $(($RANDOM%2))
      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          draft: false
          release: ${{ env.TAG }}
  rollback:
    name: Rollback the deployment
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Rolling back
        run: echo "rolling back the latest release docker to $CURRENT version!"
