---

name: ci

on:
  schedule:
    - cron: '0 1 * * *' # everyday at 1 AM
  pull_request:
  push:
    branches: master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_POWERSHELL: false # To get rid of error

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare env vars
        id: info
        run: .github/docker-env.sh
        env:
          EVENT: ${{ github.event_name }}
          EVENT_NUMBER: ${{ github.event.number }}
          GITHUB_SHA: ${{ github.sha }}
      - name: Print outputs
        run: echo ${{ steps.info.outputs.tags }}

      - name: Build and Push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/${{ github.repository }}/service
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GROUP_TOKEN }}
          registry: docker.pkg.github.com
          tags: ${{ steps.info.outputs.tags }}
