---

name: ci

on:
  schedule:
    - cron: '0 10 * * *' # everyday at 10am
  pull_request:
  push:
    branches: master

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_POWERSHELL: false

  docker:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare env vars
        id: info
        run: .github/docker-env.sh
      - name: Build and Push
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: docker.pkg.github.com/dovnaralexander/github-actions-docker-generic/service
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GROUP_TOKEN }}
          registry: docker.pkg.github.com
          tags: ${{ steps.info.outputs.tags }}
